
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Docker@2
  inputs:
    containerRegistry: 'docker hub'
    repository: 'pareenvatani/squash-url-service'
    command: 'buildAndPush'
    Dockerfile: 'dockerfile'